export interface UniversityOption {
  name: string;
  abbreviation: string;
}

export const universities: UniversityOption[] = [
  { name: "Adama Science and Technology University", abbreviation: "ASTU" },
  { name: "Addis Ababa Science and Technology University", abbreviation: "AASTU" },
  { name: "Addis Ababa University", abbreviation: "AAU" },
  { name: "Adigrat University", abbreviation: "AGU" },
  { name: "Aksum University", abbreviation: "AKU / AXU" },
  { name: "Ambo University", abbreviation: "AU" },
  { name: "Arba Minch University", abbreviation: "AMU" },
  { name: "Arsi University", abbreviation: "ARU" },
  { name: "Assosa University", abbreviation: "ASU" },
  { name: "Bahir Dar University", abbreviation: "BDU" },
  { name: "Bonga University", abbreviation: "BU" },
  { name: "Borana University", abbreviation: "BRU" },
  { name: "Bule Hora University", abbreviation: "BHU" },
  { name: "Debark University", abbreviation: "DKU" },
  { name: "Debre Berhan University", abbreviation: "DBU" },
  { name: "Debre Markos University", abbreviation: "DMU" },
  { name: "Debre Tabor University", abbreviation: "DBTU" },
  { name: "Dembi Dolo University", abbreviation: "DeDU" },
  { name: "Dilla University", abbreviation: "DU" },
  { name: "Dire Dawa University", abbreviation: "DDU" },
  { name: "Gambella University", abbreviation: "GMU" },
  { name: "Haramaya University", abbreviation: "HRU" },
  { name: "Hawassa University", abbreviation: "HWU" },
  { name: "Injibara University", abbreviation: "IU" },
  { name: "Jigjiga University", abbreviation: "JGU" },
  { name: "Jimma University", abbreviation: "JU" },
  { name: "Jinka University", abbreviation: "JNU" },
  { name: "Kebri Dehar University", abbreviation: "KDU" },
  { name: "Kotebe University of Education", abbreviation: "KUE" },
  { name: "Madda Walabu University", abbreviation: "MWU" },
  { name: "Mattu University", abbreviation: "MEU" },
  { name: "Mekdela Amba University", abbreviation: "MAU" },
  { name: "Mekelle University", abbreviation: "MU" },
  { name: "Mizan–Tepi University", abbreviation: "MTU" },
  { name: "Oda Bultum University", abbreviation: "OBU" },
  { name: "Raya University", abbreviation: "RU / RAYU" },
  { name: "Samara University", abbreviation: "SU" },
  { name: "Selale University", abbreviation: "SLU" },
  { name: "University of Gondar", abbreviation: "UoG / GU" },
  { name: "Wachamo University", abbreviation: "WCU" },
  { name: "Werabe University", abbreviation: "WRU" },
  { name: "Wolaita Sodo University", abbreviation: "WSU" },
  { name: "Woldia University", abbreviation: "WDU" },
  { name: "Wolkite University", abbreviation: "WKU" },
  { name: "Wollega University", abbreviation: "WU" },
  { name: "Wollo University", abbreviation: "WOU" },
];
